server:
  port: 9296


spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: git://github.com/ahmed-ba/config-server
          clone-on-start: true